title: AI Core Troubleshooting
description: Guides and troubleshooting tips for SAP AI Core
remote_theme: just-the-docs/just-the-docs@v0.10.0
url: ""

color_scheme: dark

aux_links:
  "GitHub":
    - "https://github.com/SmitaNaik05/aicore-troubleshooting"

aux_links_new_tab: true

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

search_enabled: true
search:
  heading_level: 3

nav_sort: order
